### ISSUE TITLE
CRUD-style support

### ISSUE THREAD

**Issue by haxsaw** [haxsaw/hikaru#14]
Add CRUD-style methods to those generated on HikaruDocumentBase subclasses. There may be cases where CRUD-like instance and static methods should be added; we need to consider what it means to issue them on either (read() on an instance vs read() on the class, for example).

**Comment by haxsaw** [comment]
NOTE TO ANYONE TRYING OUT THE CRUD FEATURE EARLY: I can say for certain the behaviour and return values are going to change, so be warned if you want to start messing around with this stuff pre-release.

**Comment by aantn** [comment]
Thanks for the heads up :)

**Comment by haxsaw** [comment]
OK, the CRUD API has settled down to where I *think* it's going to stay (barring feedback regarding changes). The CRUD methods are now:

- all instance methods
- always return self, and modify self in place if the return object is the same type
- have lost the ability to perform actions asynchronously.

So the CRUD interface is a higher-level one. Full access to all args and K8s methods is still available .

**Comment by haxsaw** [comment]
Added to 0.5b
