### ISSUE TITLE
Node from_dict fails on required field port (in DeamonEndpoint)

### ISSUE THREAD

**Issue by arikrobustatest** [haxsaw/hikaru#17]
While trying to convert k8s Node event into hikaru Node object, I get the below error.
The node yaml contains:
  daemonEndpoints:
    kubeletEndpoint:
      Port: 10250

To reproduce:
obj = hikaru.from_dict(some_node_dict, cls=Node)

Error:
   obj = hikaru.from_dict(k8s_payload.obj, cls=model_class)
  File "/usr/local/lib/python3.8/site-packages/hikaru/generate.py", line 243, in from_dict
    doc = cls.from_yaml(yaml, translate=translate)
  File "/usr/local/lib/python3.8/site-packages/hikaru/meta.py", line 455, in from_yaml
    inst.process(yaml, translate=translate)
  File "/usr/local/lib/python3.8/site-packages/hikaru/meta.py", line 832, in process
    obj.process(val, translate=translate)
  File "/usr/local/lib/python3.8/site-packages/hikaru/meta.py", line 832, in process
    obj.process(val, translate=translate)
  File "/usr/local/lib/python3.8/site-packages/hikaru/meta.py", line 832, in process
    obj.process(val, translate=translate)
  File "/usr/local/lib/python3.8/site-packages/hikaru/meta.py", line 816, in process
    raise TypeError(f"{self.__class__.__name__} is missing {k8s_name}"
TypeError: DaemonEndpoint is missing port (originally port)

**Comment by haxsaw** [comment]
Sigh. This is the only use of 'port' in the whole swagger spec that doesn't follow the capitalization conventions that the rest of the spec does for that property. It wouldn't surprise me if there were some other outliers lurking around. I'll give some thought about a good way to fix it.

**Comment by haxsaw** [comment]
This will be fixed in the forthcoming patch release. Note that in Hikaru's DaemonEndpoint object the 'port' parameter is now 'Port', which is the proper name according to Swagger and 'kubectl explain', but not in the K8s Python client (which is why there was a problem in the first place). I believe these will all be good.

**Comment by arikalon1** [comment]
Thanks for the fast fix!
