### ISSUE TITLE
List methods aren't assigned to classes consistently

### ISSUE THREAD

**Issue by haxsaw** [haxsaw/hikaru#18]
In the course of researching support for exposing K8s 'watch' functionality, it was discovered that the 'list' operations are not being consistently attached to classes as methods. For example, listNamespacedJob() is a method on the JobList class, but listJobForAllNamespaces() is a method on the Job class. The intent was that methods that return a list be attached to the list class themselves, not the class that are items in the list. For the sake of consistency, new models are needed that establish these methods on the proper class, and any changes that are made must be documented to aid anyone who has to alter code due to this method refactor.

**Comment by aantn** [comment]
Cool, thank you for doccumenting this.

**Comment by haxsaw** [comment]
The changes in method-class associations for release 0.7 are documented in the new release_notes.txt for the upcoming release.

You can view that file now at: https://github.com/haxsaw/hikaru/blob/226f06606cc9b1db5dcb9e79f584f114edab9e21/release_notes.rst

**Comment by aantn** [comment]
Thank you!

**Comment by haxsaw** [comment]
Fixed in 0.7b
