### ISSUE TITLE
convert underscore to dash implicitely in _clean_dict may introduce in un-expected labels

### ISSUE THREAD

**Issue by jizhilong** [haxsaw/hikaru#21]
Hi @haxsaw 
The replacement in https://github.com/haxsaw/hikaru/blob/main/hikaru/generate.py#L84 may implicitely convert a custom label `my_app` into `my-app`, which is not needed in most scenarios. Is this a designed feature or a bug?

**Comment by haxsaw** [comment]
Nuts. Yeah, this was to solve a particular problem, but I didn't think it through for all cases. I'll come up with a fix.

**Comment by jizhilong** [comment]
> this was to solve a particular problem

Would you mind to share some details of the problem?

**Comment by pyfdtic** [comment]
@haxsaw we try to fix this issue, plz help us with it and review this pr https://github.com/haxsaw/hikaru/pull/24

**Comment by haxsaw** [comment]
I hope you saw the new release that has a patch for your issue. Let me know if that solves it.

**Comment by jizhilong** [comment]
Hi @haxsaw sorry for the late responding. Since we are still using version 0.5.1b0, and upgrading to the latest would cause a lot of breaks, I cant test your fix in production, and work around this issue by using label names with dashs instead of with underlines. Howeveer,  as what I saw in unit tests in other projects, I believe this fix works in a lot of scenarios, so feel free to close this issue.
