### ISSUE TITLE
Support for K8s v1.25

### ISSUE THREAD

**Issue by Sharpz7** [haxsaw/hikaru#32]
Are there any plans on releasing new versions?

**Comment by haxsaw** [comment]
Yeah, sorry-- a release is actually in the works, and I'm just doing document tidying, but life is kind of getting in the way. The code is finished and the doc review is about 70% done, so it's fairly close, but finding time has been challenging. I will try to make this happen soon.

**Comment by Sharpz7** [comment]
Thank you! If you need any help, just let me know :))

**Comment by haxsaw** [comment]
Hey @Sharpz7 , I just wanted to follow up on this as it's been a while. I've actually had a release candidate for some time now, however I'm being thwarted in doing a final release I'm happy with as I'm getting some weird artifacts in my test bed. Resources are deleting, but k3s isn't allowing them to actually disappear. This is thwarting full integration testing, and I'm kind of a bit obsessive that this goes through successfully before I do a release.

If you don't want to wait until I figure this out, I'd be willing to do a pre-release for the next version. There will be no promises made here as I'm trying to sort out these problems (I suspect an update on my testbed for something has caused this), but it would allow you to move forward until I got these issues addressed.

Is this something you'd like to get your hands on?

**Comment by haxsaw** [comment]
Just to keep this alive, I've just released support for 23.x of the K8x client. This release will (hopefully) make adding support for new releases easier,  but I've never failed to run into at least a few headaches every time I have to process a new swagger file.

If you're dying for support of 25.x DM me and we can talk about what's involved.

**Comment by haxsaw** [comment]
Support for 24.x, 25.x, and 26.x just released. :-)
