### ISSUE TITLE
Import errors

### ISSUE THREAD

**Issue by aantn** [haxsaw/hikaru#35]
# Error

On my local machine, the following fails:

```
from hikaru.model.rel_1_26 import ContainerStatus, Pod
```

with a strange error:

```
ImportError: cannot import name 'ContainerStatus' from 'hikaru.model.rel_1_26' (/Users/natanyellin/Library/Caches/pypoetry/virtualenvs/robusta-cli-k1xMhET--py3.9/lib/python3.9/site-packages/hikaru/model/rel_1_26/__init__.py)
```

Of course, `ContainerStatus` does in fact exist in the right place.

# Investigation

If I patch `site-packages/hikaru/model/rel_1_26/v1/__init__.py` as follows:

```
try:
    from .v1 import *
except ImportError as e:  # pragma: no cover
    print("Whoops", e)
    pass
```

We discover the real cause:

```
Whoops cannot import name 'CertificatesV1Api' from 'kubernetes.client' (/Users/natanyellin/Library/Caches/pypoetry/virtualenvs/robusta-cli-k1xMhET--py3.9/lib/python3.9/site-packages/kubernetes/client/__init__.py)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'ContainerStatus' from 'hikaru.model.rel_1_26' (/Users/natanyellin/Library/Caches/pypoetry/virtualenvs/robusta-cli-k1xMhET--py3.9/lib/python3.9/site-packages/hikaru/model/rel_1_26/__init__.py)
```

hikaru is trying to import `CertificatesV1Api` which doesn't exist in the minimum version of `kubernetes-client` that hikaru requires. (All of hikaru's python dependencies are satisfied on my machine, although some libraries like `kubernetes-client` are running a compatible but not latest version.)

If I update my local `kubernetes-client` version to the latest this problem resolves itself.

# Suggestions
1. Update the minimum `kubernetes-client` version (not sure what's the real minimum, just know that latest works for me)
2. Maybe don't do a blanket `pass` on ImportErrors? It makes troubleshooting stuff like this a little hard.

**Comment by aantn** [comment]
OK, it looks like I might have been too quick to blame hikaru here.

Sorry about that. We're doing something on our end that might be impacting the dependency and reverting it to something lower. Feel free to close.

**Comment by haxsaw** [comment]
Hey, np. Happy for the feedbak.
