### ISSUE TITLE
Kubernetes 409 when updating CRD with context manager

### ISSUE THREAD

**Issue by cmac4603** [haxsaw/hikaru#37]
Hello! I'm having an issue when using the context manager with a CRD. I have the following code where I have got a **new version** of a CRD created, the code then reads the new_crd CRD and makes some updates and then calls the `update()` CRUD method. When I run this the update actually works, but an exception is caught when the k8s API throws a 409.

```python
try:
    with rollback_cm(MyCRD(metadata=ObjectMeta(name=new_crd.metadata.name)).read()) as obj:
        obj.spec = new_crd.spec
        obj.metadata.annotations = new_crd.metadata.annotations
        obj.status = {"status": "updated"}
        obj.update(dry_run=dry_run_directive)
except Exception:
    # always 409 
```
In the logs I see:
```console
[2024-03-05 19:54:12,783] kubernetes.client.re [DEBUG   ] response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Operation cannot be fulfilled on mycrd.app.com \"my-app-0
\": the object has been modified; please apply your changes to the latest version and try again","reason":"Conflict","details":{"name":"my-app-0","group":"app.com","kind":"mycrd"},"code":409}
```

But like I said, the change has been applied. Is this something anyone has seen before?

**Comment by cmac4603** [comment]
I should add, I'm not seeing the same thing with k8s own resource definitions like `Ingress`.

**Comment by cmac4603** [comment]
Never mind, it was because I was changing the status 😞

**Comment by haxsaw** [comment]
I can say that I have seen that recently created and read resources sometimes don't take updates; some event can occur in the cluster that changes the status in some small way, and then updates fail. I have to make allowances for this in the integration testing; often I need to read the objects a couple of times before updating as the state hasn't seemed to settle down. I have to admit I don't much like this experience and would be open to ideas to make it better.

**Comment by cmac4603** [comment]
Yeah. I'm seeing this as well, and retrying eventually takes but it's because of other operators running on the k8s cluster. I'm not sure it would be ok to just ignore these changes, but failing and retrying until it takes is strange for an end user as well. I'm going to be looking into this more soon because the retrying is not ideal, if I figure something out or think of any ideas I'll come back here as it's a curious problem to overcome
