### ISSUE TITLE
Do you support openshift?

### ISSUE THREAD

**Issue by anthcp-infocom** [haxsaw/hikaru#6]
Do you plan to support OpenShift?
If not please ignore or delete this issue.
If you do then I have converted the openshift swagger file to version 3 of the open API but it fails the build process with an error;
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/anthcp/code/hikaru-oc/hikaru/build.py", line 556, in <module>
    build_it(sys.argv[1])
  File "/Users/anthcp/code/hikaru-oc/hikaru/build.py", line 547, in build_it
    load_stable(swagger_file)
  File "/Users/anthcp/code/hikaru-oc/hikaru/build.py", line 218, in load_stable
    for k, v in d["definitions"].items():
KeyError: 'definitions'

I have attached the swagger json file...
[openapi-v3.json.gz](https://github.com/haxsaw/hikaru/files/6370944/openapi-v3.json.gz)

**Comment by anthcp-infocom** [comment]
I managed to get OpenSift Routes working by adding the Route components from the openapi-v3.json to your original open API file... However, to get the get_yaml() function to work properly on my OSX Mac, I had to use PyYaml as I was getting dictionary's listed in the list values as {} etc...

**Comment by haxsaw** [comment]
I hadn't considered OpenShift support; I've currently been working on connecting Hikaru to the Kubernetes Python client so sending requests is a little more seamless, and was planning subsequently to improve the API in Hikaru to offer a CRUD-like experience. This is an interesting notion though, but I think the build system will need some work as there are lots of artefacts that reflect the inconsistencies in the Kubernetes swagger file. I'm happy for you to leave this as an open request, but I can't make any representations at the moment.

**Comment by haxsaw** [comment]
This is making me think that the builder might be something to pull out into an independent project. It will need some work to separate out the quirks from straightforward processing. Are you using the dev branch or the main one?

**Comment by haxsaw** [comment]
Well cool! I guess I'll close this out then, but if you want to revisit in the future then just open again or create a new one.
